-- MySQL Script generated by MySQL Workbench
-- Wed Jan  13 19:23:35 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`buyers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`buyers` (
  `id_buyer` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `region` VARCHAR(45) NULL,
  `sale` DOUBLE NULL,
  PRIMARY KEY (`id_buyer`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`shop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`shop` (
  `id_shop` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `region` VARCHAR(45) NULL,
  `commission` DOUBLE NULL,
  PRIMARY KEY (`id_shop`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`books` (
  `id_book` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `price` DOUBLE NULL,
  `region` VARCHAR(45) NULL,
  `qty` INT NULL,
  PRIMARY KEY (`id_book`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`purchase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`purchase` (
  `id_purchase` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  `shop` INT NULL,
  `buyer` INT NULL,
  `book` INT NULL,
  `qty` INT NULL,
  `total` DOUBLE NULL,
  PRIMARY KEY (`id_purchase`),
  CONSTRAINT `id_buyer_fk`
    FOREIGN KEY (`buyer`)
    REFERENCES `mydb`.`buyers` (`id_buyer`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `id_book_fk`
    FOREIGN KEY (`book`)
    REFERENCES `mydb`.`books` (`id_book`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `id_shop_fk`
    FOREIGN KEY (`shop`)
    REFERENCES `mydb`.`shop` (`id_shop`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;
